version: '3.6'
services:
  api:
    container_name: todo-api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: src/services/api
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    depends_on: ["db"]

  notifier:
    container_name: notifier
    image: ${DOCKER_REGISTRY-}notifier
    build:
      context: src/services/notifier
      dockerfile: Dockerfile
    depends_on: [ "rabbitmq" ]

  db:
    container_name: database
    image: ${DOCKER_REGISTRY-}db
    build:
      context: sql
      dockerfile: Dockerfile
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user1
      - RABBITMQ_DEFAULT_PASS=pass1
      - RABBITMQ_DEFAULT_VHOST=didi
